### ISSUE TITLE
support for dashes ('-') in apiary_managed_schemas

### ISSUE THREAD

**Issue by vishalsingla2004** [ExpediaGroup/apiary#5]
As a user variable 'apiary_managed_schemas' currently does allow me to specify dashes ('-') in the name e.g. abc-dm but since the same variable is used to create hive schema it makes it unusable since hive does not live dashes in the name.

**Comment by pradeepbhadani** [comment]
Relevant PR - https://github.com/ExpediaInc/apiary-data-lake/pull/96
https://github.com/ExpediaInc/apiary-metastore-docker/pull/44

**Comment by pradeepbhadani** [comment]
Resolved by https://github.com/ExpediaGroup/apiary-data-lake/pull/105 and https://github.com/ExpediaGroup/apiary-metastore-docker/pull/52
